### ISSUE TITLE
项目部署失败

### ISSUE THREAD

**Issue by amoyiki** [CoderDream/sshe#1]
下载下来部署了一下发现项目有些问题。我已经修改成功了，告知一下。

action下面的struts.xml应该转移到资源文件夹/src/main/resources下，为了防止冲突应该改成其他名字。
如果不将action包下的struts.xml一出来会导致struts.xml 内的package extends="struts-base" 继承不成功。

**Comment by coderdream** [comment]
不知道你用的什么IDE，我用eclipse Java EE 4.4.x没有问题。
